apiVersion: v1
kind: Secret
metadata:
  name: avp-backend-config
  namespace: argocd
type: Opaque
stringData:
  AVP_TYPE: vault
  AVP_AUTH_TYPE: token
  VAULT_ADDR: http://vault.default:8200
  VAULT_TOKEN: <your-vault-token>
