---
# Path Annotation
kind: Secret
apiVersion: v1
metadata:
  name: vault-path-annotation
  annotations:
    avp.kubernetes.io/path: "secret/data/database"
type: Opaque
data:
  username: <username>
  password: <password>
---
# Inline Path
kind: Secret
apiVersion: v1
metadata:
  name: vault-inline-path
type: Opaque
data:
  username: <path:secret/data/database#username>
  password: <path:secret/data/database#password>
---
# Versioned secrets
kind: Secret
apiVersion: v1
metadata:
  name: vault-versioned-secrets
  annotations:
    avp.kubernetes.io/path: "secret/data/database"
    avp.kubernetes.io/secret-version: "2" # 2 is the latest revision in this example
type: Opaque
data:
  username: <username>
  password: <password>
  username-current: <path:secret/data/database#username#2> # same as <username>
  password-current: <path:secret/data/database#password#2> # same as <password>
  username-old: <path:secret/data/database#username#1>
  password-old: <path:secret/data/database#password#1>