# manifest with placeholder
#   AVP replace the placeholder -- with the -- value | Vault
# Vault path: kv/data/test (KV v2 requires /data/ in the path)
apiVersion: v1
kind: Secret
metadata:
  name: avp-test-secret
  annotations:
    avp.kubernetes.io/path: "kv/data/test"
type: Opaque
stringData:
  # character
  #   == key | Vault
  character: <character>
