apiVersion: v1
data:
  # keys
  #   case-sensitive
  VAULT_ADDR: Zm9v
  #     NOT understood -- by -- ArgoCD Vault plugin
  vault_addr: Zm9v

  # data's values
  #   base64
  AVP_AUTH_TYPE: Zm9v
  AVP_GITHUB_TOKEN: Zm9v
  AVP_TYPE: Zm9v
kind: Secret
metadata:
  name: vault-configuration
  namespace: argocd
type: Opaque