apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: vault-configuration
  namespace: argocd
data:
  # keys
  #   case-sensitive
  VAULT_ADDR: Zm9v
  #     NOT understood -- by -- ArgoCD Vault plugin
  vault_addr: Zm9v

  # data's values
  #   base64
  AVP_AUTH_TYPE: Zm9v
  AVP_GITHUB_TOKEN: Zm9v
  AVP_TYPE: Zm9v
stringData:
  # stringData's values
  #   raw text (!= base64)
  AVP_SECRET_ID: "my-secret-id-in-plain-text"
  # ArgoCD, | BEFORE reaching the plugin, prefix them
  #   ARGOCD_ENV_AVP_SECRET_ID
