apiVersion: v1
kind: Secret
metadata:
  name: vault-configuration
type: Opaque
stringData:
  VAULT_ADDR: "http://vault.default.svc:8200"
  AVP_TYPE: "vault"
  AVP_AUTH_TYPE: "token"
  VAULT_TOKEN: "<VAULT_TOKEN>"
  AVP_KV_VERSION: "2"
